name: Build

on:
  push:
    branshes: [ $default-branch, build ]
    # Sequence of patterns matched against refs/tags
    #tags:
    #- 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64]
    name: Build on Windows ${{ matrix.architecture }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_win.txt
      - name: Build
        run: |
          python setup_.py build
      - name: Generate installer
        run: |
          python setup_.py bdist_msi
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.msi

# vim: ts=2 sw=2 et
